### ISSUE TITLE
Add RTMP/RTSP input support

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-streamer#16]
Similar to #9 (UDP input support), we should add support for RTMP/RTSP input.

It may also be worth considering an input type that allows the user to connect an arbitrary ffmpeg command line as input, rather than adding explicit support for many various inputs types that ffmpeg supports.

**Comment by joeyparrish** [comment]
(Suggested by @Romantic-LiXuefeng in #15.)

**Comment by joeyparrish** [comment]
We've just discovered through the conversation in #42 that RTMP doesn't seem to need any additional work. Just documentation.

Here's a working RTMP input config, for example:

```yaml
inputs:
  - name: rtmp://localhost/live/foo
    media_type: video

  - name: rtmp://localhost/live/foo
    media_type: audio
```
