### ISSUE TITLE
Multiple audio codecs in HLS output can't be played in Shaka Player

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-streamer#18]
It's not yet clear if this should be restricted in Streamer, tweaked in Packager, or improved in Player.

For now, restrict yourself to aac for HLS.

**Comment by joeyparrish** [comment]
Packager's dash_only=1 should solve this: https://google.github.io/shaka-packager/html/tutorials/dash.html

Not sure if we should hard-code a dash_only=1 on WebM-format outputs (much simpler), or if we should make dash_only configurable in the bitrate/codec configs (more extensible).

**Comment by CaitlinOCallaghan** [comment]
@joeyparrish, to clarify, if the pipeline config includes the following:


```
# The codecs to encode with.
audio_codecs:
  - aac
  - ac3
  - opus
video_codecs:
  - h264
  - vp9

# Manifest format (dash, hls or both)
manifest_format:
  - dash
  - hls
```

Shaka Player will not be able to properly handle the HLS stream? So, we would want something like this to restrict HLS to only aac:

```
# The codecs to encode with.
audio_codecs:
  aac:
    dash_only: False
  ac3:
    dash_only: True
  opus:
    dash_only: True
video_codecs:
  - h264
  - vp9

# Manifest format (dash, hls or both)
manifest_format:
  - dash
  - hls 
```

If we go with the configurable approach, do we want to allow users be able to restrict any codec to "dash_only", or just opus since [it's the only one that maps to a webm formatted output](https://github.com/google/shaka-streamer/blob/master/streamer/bitrate_configuration.py#L60)?
