### ISSUE TITLE
Generate multi-period output

### ISSUE THREAD

**Issue by Angels-group** [google/shaka-streamer#43]
It would be very nice to get the playlist function. In order to be able to transfer as an argument xml (or json) a file with a list of media files that will be converted to m3u8 or mpd playlist in turn (non-stop stream).
This is one of the most anticipated features.

**Comment by joeyparrish** [comment]
Let me see if I understand correctly.  You want Shaka Streamer to stitch together multiple inputs into a continuous output?

**Comment by Angels-group** [comment]
Yes something like that.
I imagine it this way: there is a certain json file, to which there is an array of file names and configurations to it.

Just for example:
```
{
  "input_config": "input.yaml",
  "pipeline_config": "pipeline.yaml",
  "files": [
  {
    "source": "file1.mp4"
  },
  {
    "source": "file2.mp4"
  },
  {
    "source": "file3.mp4"
  }
  ]
}
```

At the output, we get an hls / dash playlist.
If we used the Live type, the files are encoded one by one. As when playing a playlist in the usual sense. Something like a TV broadcast with a schedule of movies / shows / music videos (and so on). If we choose the VOD type, we get an hls / dash playlist with a duration equal to the sum of the durations of all the files added to the json playlist (which I presented above)

**Comment by joeyparrish** [comment]
I think for us, this would be a new type of input in the input.yaml file.  But I'm not sure how we would design it offhand.  I'll rename the issue and leave this as a feature request in our backlog, but we'd be happy to discuss a design here and review your pull request if you want to tackle it yourself.

**Comment by joeyparrish** [comment]
Rough proposal for the input config:

```yaml
inputs:
    # The type of input.
  - input_type: concat
    # The media type is required at this level only.
    media_type: video
    list:
      # These only need to have "name" attributes.
      -name: foo1.mp4
      -name: foo2.mp4
       is_interlaced: True  # If you have an interlaced source in the list

    # The type of input.
  - input_type: concat
    # The media type is required at this level only.
    media_type: audio
    language: "de"
    list:
      # These only need to have "name" attributes.
      -name: foo1.mp4
      -name: foo2.mp4
       track_num: 2  # If the 0th audio track is not the one you want here...
```
