### ISSUE TITLE
DASH VOD output appears to be live

### ISSUE THREAD

**Issue by bkodirov** [google/shaka-streamer#61]
The output of the down below pipeline_config.yaml is producing an MPD with type="dynamic"

```yaml
streaming_mode: vod

resolutions:
  - 1080p
  - 720p
  - 480p
  - 360p

channels: 2

audio_codecs:
  - aac
video_codecs:
  - h264

manifest_format:
  - dash
  - hls

segment_size: 10
segment_per_file: True
dash_output: manifest.mpd
hls_output: manifest.m3u8
```

Here is the beginning of the Dash manifest
```xml
<MPD
  xmlns="urn:mpeg:dash:schema:mpd:2011"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd"
  profiles="urn:mpeg:dash:profile:isoff-live:2011"
  minBufferTime="PT2S"
  type="dynamic"
  publishTime="2020-06-30T03:12:12Z"
  availabilityStartTime="2020-06-30T03:05:55Z"
  minimumUpdatePeriod="PT5S"
  timeShiftBufferDepth="PT1800S">
```

Using:
- Shaka Streamer v0.3.0
- ffmpeg version 4.2.1 
- packager version v2.4.2-c60e988-release
