### ISSUE TITLE
Add UDP input support

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-streamer#9]
We don't yet support UDP input streams, but we could.

**Comment by joeyparrish** [comment]
RTMP and UDP inputs seem to work without any additional code.  How to use them should be well-documented, though, so I'm changing this to a docs issue.

**Comment by LSrt-stack** [comment]
Could we have sample config files for RTMP and UDP inputs ?  Thank you

**Comment by okejadi** [comment]
hello @joeyparrishm can I see the sample for udp inputs? 

I tried this:

```
# List of inputs.
inputs:
    # The type of input.
#  - input_type: external_command
    # The command to run.  Here $SHAKA_STREAMER_EXTERNAL_COMMAND_OUTPUT
    # (or %SHAKA_STREAMER_EXTERNAL_COMMAND_OUTPUT% on Windows) is replaced
    # with the output pipe.
  - name: udp://@227.10.20.8:1234
    media_type: video
    # hardcode resolution to avoid autodetection
    resolution: 720p
    frame_rate: 25

#  - input_type: external_command
  - name: udp://@227.10.20.8:1234
    media_type: audio
    channel_layout: stereo
```

but it got stuck

![image](https://github.com/shaka-project/shaka-streamer/assets/35001086/d2fbcf54-870b-4085-8e1d-dac070be2ec8)

any suggestions?
